context:
  name: wagtail-draftail-plugins
  version: "0.3.1"

package:
  name: wagtail-draftail-plugins
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_draftail_plugins-{{ version }}.tar.gz
  sha256: 8cbd2e79d1d951f3e2753a1c80644db66cf86ddc5897caf9c69f043311e1a8de

build:
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
    - versiontag >=1.2.0
  run:
    - python >=${{ python_min }}
    - wagtail >=4.0

tests:
  - python:
      imports:
        - wagtail_draftail_plugins
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script: pip check

about:
  homepage: https://gitlab.com/thelabnyc/wagtail-draftail-plugins
  license: MIT
  license_file: LICENSE
  summary: Commonly used extensions to Wagtail's Draftail editor.
  description: |
    This library includes some commonly used extensions for the Wagtail Draftail editor.
  documentation: https://gitlab.com/thelabnyc/wagtail-draftail-plugins/-/blob/master/README.rst
  repository: https://gitlab.com/thelabnyc/wagtail-draftail-plugins

extra:
  recipe-maintainers:
    - rxm7706
